-- CareSync 2.0 Master Schema
-- Run this in the Supabase SQL Editor to fix "schema cache" errors

-- Reset
DROP TABLE IF EXISTS insurance_suggestions;
DROP TABLE IF EXISTS extracted_data;
DROP TABLE IF EXISTS users;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
CREATE TABLE public.users (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

  full_name TEXT,
  date_of_birth DATE,
  age INT,
  gender TEXT,
  phone_number TEXT,
  address TEXT,

  blood_group TEXT,
  allergies TEXT,
  chronic_diseases TEXT,
  past_medical_history TEXT,
  current_medications TEXT,

  smoking BOOLEAN,
  alcohol_consumption BOOLEAN,
  exercise_frequency TEXT,
  height_cm INT,
  weight_kg INT,

  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  family_medical_history TEXT,
  ongoing_treatments TEXT,

  created_at TIMESTAMP DEFAULT NOW()
);

-- Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all"
ON public.users
FOR ALL
TO public
USING (true)
WITH CHECK (true);

-- Optional: Re-create secondary tables if needed
CREATE TABLE public.extracted_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  conditions TEXT[],
  allergies TEXT[],
  medications TEXT[],
  summary TEXT,
  risk_level TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE public.insurance_suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  risk_level TEXT,
  suggested_plan TEXT,
  reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.extracted_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insurance_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all" ON public.extracted_data FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON public.insurance_suggestions FOR ALL TO public USING (true) WITH CHECK (true);
CREATE TABLE public.reports (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  title TEXT,
  file_url TEXT,
  extracted_text TEXT,
  summary TEXT,
  conditions JSONB,
  medications JSONB,
  tests TEXT[],
  dates TEXT[],
  risk_level TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON public.reports FOR ALL TO public USING (true) WITH CHECK (true);
